trigger:
- master

pr:
- master

pool:
  vmImage: 'win1803'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 10.x'

- script: |
    npm install -g npm@6.9.0
    npm run prepare - successful
  displayName: 'Temp npm version set'

- template: templates/yml/node/combo/npm-coverage-validation-xunit-cobertura.yml@templates
  parameters:
    publishTestResults:
      taskDisplayName: 'Publish unit test results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'xunit.xml'
      searchFolder: '$(Build.SourcesDirectory)/.testresults/unit'
      testRunTitle: 'vscode-rust-test-adapter::Unit Tests::Windows PR - Build $(Build.BuildId)'

